// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250318223409_TestData")]
    partial class TestData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("API.Entity.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int?>("stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "telephone",
                            ImageUrl = "1.jpg",
                            IsActive = true,
                            Name = "Iphone14",
                            Price = 7000m,
                            stock = 4
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "telephone",
                            ImageUrl = "2.jpg",
                            IsActive = true,
                            Name = "Iphone15",
                            Price = 5000m,
                            stock = 9
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "telephone",
                            ImageUrl = "3.jpg",
                            IsActive = true,
                            Name = "Iphone16",
                            Price = 2000m,
                            stock = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
